### ISSUE TITLE
Convert into Python Package

### ISSUE THREAD

**Issue by amitness** [studenton/QuakeCL#1]

**Comment by amitness** [comment]
https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/index.html

**Comment by markvl** [comment]
I'll pick up this one.

**Comment by markvl** [comment]
I have submitted a pull request (#4). I hope it was what you expected. Otherwise, let's discuss.

**Comment by amitness** [comment]
@markvl Thanks mark. I'm guessing I've to upload it to Pypi for this to work, right?

```
pip install QuakeCL
```

**Comment by markvl** [comment]
@amitness That is correct.

But I can also remove the 'remove install.sh' commit and undo that change in the README if you want to. I will replace the code in that install script to not do a manual copy of the Python file but a 'proper' installation. Would you rather have that?

**Comment by amitness** [comment]
@markvl  Nope, just wanted to confirm so that I'll upload it now. Thanks a lot for this.

**Comment by markvl** [comment]
Glad you found my contribution useful.
